# Generated by Django 3.2.25 on 2025-01-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='user',
        ),
    ]
